ChapKhoone/ChapKhoone/urls.py
from django.contrib.staticfiles.urls import static
from django.contrib import admin
from django.urls import path, include
from . import settings
from account.views import AboutUs, CartDetail, StampByCategory, StampList, contact_form, search, Landing, LoginView, RegisterView, VerifyView, ResendVerifyView, NotpermissionOr404, stamp_detail








urlpatterns = [
                  path('grappelli/', include('grappelli.urls')),
                  path('admin/', admin.site.urls),
                  
                  path('acoounts/login/', LoginView.as_view(), name='login-not-auth'),
                  path('acoounts/verify-phone-number/', VerifyView.as_view(), name='verify'),
                  path('acoounts/verify-phone-number/resend/', ResendVerifyView.as_view(), name='resend'),
                  path('acoounts/register/', RegisterView.as_view(), name='register-not-auth'),

                  path('acoounts/', include('django.contrib.auth.urls')),
                  
        
                  path('error-404/', NotpermissionOr404.as_view(), name='not-permission'),
                  path('', Landing, name='landing-home'),
                  
                  path('dashboard/', include('account.urls')),
                  path('search/', search, name='search'),
                  path('about-us/', AboutUs.as_view(), name='about-us'),
                  path('contact-us/', contact_form, name='contact-us'),
                  path('stamp/', StampList.as_view(), name='stamp-list'),
                  path('stamp/<slug:slug>/', StampByCategory.as_view(), name='stamp-category'),
                  path('stamp-detail/<slug:slug>/', stamp_detail, name='stamp-detail'),
                  path('cart-detail/<int:pk>', CartDetail.as_view(), name='cart-detail')
                  
    

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ChapKhoone/account/urls.py
from django.urls import path

from .views import Dashboard, UserEditView, invite_code


urlpatterns = [
    
        path('', Dashboard, name='dashboard'),
        path('profile/', UserEditView.as_view(), name='profile'),
        path('invite-code/', invite_code, name='invite-code')
]

ChapKhoone/account/models.py
from datetime import datetime
import random
from unicodedata import category
from django.conf import settings
from django.contrib.auth.models import BaseUserManager
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
from django.urls import reverse
from django.utils.translation import ugettext as _
import pyotp
from django.template.defaultfilters import slugify
from django.utils.crypto import get_random_string
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation




class UserManager(BaseUserManager):
   
    def create_user(self, username, email, phone, password, **extra_fields):
        """
        Create and save a User with the given email, phone number and password.
        """
        if not email:
            raise ValueError('ایمیل باید وارد شود')
        if not phone:
            raise ValueError('شماره همراه باید وارد شود')
        email = self.normalize_email(email)
        user = self.model(email=email, phone=phone, username=username, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    

    def create_superuser(self, username, email, phone, password, **extra_fields):
        """
        Create and save a SuperUser with the given email, phone number and password.
        """

        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self.create_user(username, email, phone, password, **extra_fields)
    
    
    
    
    
def unique_slugify(instance, slug):
    model = instance.__class__
    unique_slug = slug
    while model.objects.filter(slug=unique_slug).exists():
        unique_slug = slug + str(random.randint(0, 12000))
    return unique_slug






class Country(models.Model):
    name = models.CharField(_("name of country"), max_length=50)

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(_("name of city"), max_length=50)
    country = models.ForeignKey(Country, verbose_name=_("country of city"), on_delete=models.CASCADE)


    def __str__(self):
        return self.name




class CustomUser(AbstractUser):
    phone_regex = RegexValidator( regex = '^9\d{9}$', message ="شماره همراه باید به فرمت (9xxxxxxxxx) وارد شود.")
    phone = models.CharField(_('شماره همراه'),validators =[phone_regex], max_length=10, unique=True,null=True)
    email = models.EmailField(_('آدرس ایمیل'), unique=True)
    REQUIRED_FIELDS = ['email', 'phone']
    is_verified = models.BooleanField('تایید شد', default=False, help_text='Designates whether this user has verified phone')
    key = models.CharField(max_length=100, unique=True, blank=True)



    objects = UserManager()  


    def __str__(self):
        return f'{self.phone} / {self.username}' 
    
    def authenticate(self, otp):
        """ This method authenticates the given otp"""
        provided_otp = 0
        try:
            provided_otp = int(otp)
        except:
            return False
        #Here we are using Time Based OTP. The interval is 60 seconds.
        #otp must be provided within this interval or it's invalid
        t = pyotp.TOTP(self.key, interval=300)
        return t.verify(provided_otp)
    
    
        

class Profile(models.Model):
    Male= 'male'
    Female= 'fmle'
    STATUS= [
        (Male, 'مذکر'),
        (Female, 'مونث'),
    ]
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE,related_name="profile")
    first_name = models.CharField(_("نام"), max_length=50)
    last_name = models.CharField(_("نام خانوادگی"), max_length=50)
    invite_code = models.CharField(_("کد معرفی "), max_length=20, unique=True)
    description = models.TextField(_("بیوگرافی"), null=True, blank=True)
    address = models.CharField(_("آدرس"),max_length=30,blank=True)
    date_joined = models.DateTimeField(_("تاریخ پیوستن"),auto_now_add=True)
    age = models.PositiveIntegerField(_("سن"),null=True, blank=True)
    sexuality = models.CharField(_("جنسیت"), max_length=4, choices=STATUS, default=Male)
    updated_on = models.DateTimeField(_("تاریخ ویرایش"),auto_now=True)
    image = models.ImageField("عکس کاربر",upload_to='uploads/profile', height_field=None, width_field=None, max_length=None, null=True, blank=True)
    city = models.ForeignKey(City, verbose_name=_("شهر"), on_delete=models.CASCADE, null=True, blank=True)
    use_invite_code = models.BooleanField(_("استفاده از کد معرف"), default=False)
    

    def __str__(self):
        return self.user.username
    
    

class Wallet(models.Model):
    user = models.OneToOneField(CustomUser,on_delete=models.CASCADE,related_name="wallet")
    date_create = models.DateTimeField(_("تاریخ ایجاد"), auto_now=False, auto_now_add=True)
    cash = models.PositiveIntegerField(_("موجودی کیف پول"), default=0)

    def __str__(self):
        return f'{self.user.username} / {self.cash}'
   
   
   
    
    
class Transaction(models.Model):
    TYPE = (("1", "واریز"), ("2", "برداشت"))
    wallet = models.OneToOneField(Wallet, verbose_name=_("کیف پول"), on_delete=models.CASCADE)
    date_transaction = models.DateTimeField(_("تاریخ تراکنش"), auto_now=True, auto_now_add=False)
    type = models.CharField(_("نوع تراکنش"), max_length=1, choices=TYPE)
    amount = models.PositiveIntegerField(_("مبلغ تراکنش"))
    
    def __str__(self):
        return f'{self.wallet} / {self.type}'
    
    
    
    
class Service(models.Model):
    name = models.CharField(_("نام سرویس"), max_length=50)
    slug = models.SlugField(_("اسلاگ"), blank=True)
    available = models.BooleanField(_("در دسترس"))
    short_description = models.CharField(_("توضیح کوتاه "), max_length=50)
    
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, slugify(self.name))
        super().save(*args, **kwargs)
    
    
    def get_absolute_url(self):
        return reverse("services", kwargs={"slug": self.slug})
    
    
class CategoryStamp(models.Model):
    name = models.CharField(_("نام دسته بندی مهر"), max_length=50)
    slug = models.SlugField(_("اسلاگ"), blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, slugify(self.name))
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name}'

    def get_absolute_url(self):
        return reverse("stamp-category", kwargs={"slug": self.slug})
    
    
    
    
    
class EssenceStamp(models.Model):
    name = models.CharField(_("رنگ جوهر مهر"), max_length=50)
    slug = models.SlugField(_("اسلاگ"), blank=True)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, slugify(self.name))
        super().save(*args, **kwargs)
        
    def __str__(self):
        return f'{self.name}'



class ShapeStamp(models.Model):
    name = models.CharField(_("شکل مهر"), max_length=50)
    slug = models.SlugField(_("اسلاگ"), blank=True)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = unique_slugify(self, slugify(self.name))
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.name}'
   
    
    
    
    
    
    
    
class Cart(models.Model):
    Paid = 'PID'
    Confirmed = 'CFD'
    Canceled = 'CNL'
    Pending = 'PND'
    CHOICES = [(Paid, 'پرداخت شده'),(Canceled, 'کنسل شده'),(Pending, 'در حال پردازش'), (Confirmed, 'تایید شده')]
    status_payment = models.CharField(_("وضعیت پرداخت"),max_length=3,choices= CHOICES, default=Pending)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.DO_NOTHING)
    order_number = models.CharField(_("شماره سفارش"),max_length=23, null=True, blank=True, unique=True)
    created_at = models.DateTimeField(_("تاریخ ایجاد"),auto_now_add=True)
    paid_amount = models.PositiveIntegerField(_("قیمت پرداختی"), blank=True, null=True)
    paid_date = models.DateTimeField(_("تاریخ پرداخت"),null=True, blank=True)
    cartitem = GenericRelation('account.cartitem')

    class Meta:
        ordering = ('-created_at',)
    
    def __str__(self):
        return f'{self.user}/{self.status_payment}/{self.order_number}'

    def save(self, *args, **kwargs):
        final_price = 0
        items = self.cartitem_set.all()
        for item in items:
            price = item.price
            quantity = item.quantity
            final_price += price * quantity
        self.paid_amount = final_price
        if not self.order_number:
            self.order_number = str(get_random_string(length=2)) + str(random.randint(1000, 9999)) + str(self.pk)
        if self.status_payment == 'PID':
            self.paid_date = datetime.now()
        super().save(*args, **kwargs)


class Stamp(models.Model):
    name = models.CharField(_("اسم مهر"), max_length=50)
    image = models.ImageField(_("عکس مهر"), upload_to='uploads/stamp', height_field=None, width_field=None, max_length=None)
    price = models.PositiveIntegerField(_("قیمت مهر"))
    category = models.ForeignKey(CategoryStamp, verbose_name=_("دسته بندی مهر"), on_delete=models.CASCADE)
    essence_color = models.ManyToManyField(EssenceStamp, verbose_name=_("رنگ جوهر"))
    height = models.PositiveIntegerField(_("ارتفاع"))
    width = models.PositiveIntegerField(_("عرض"))
    length = models.PositiveIntegerField(_("طول"))
    shape = models.ForeignKey(ShapeStamp, verbose_name=_("شکل مهر"), on_delete=models.CASCADE)
    is_bung = models.BooleanField(_("دارای درپوش"))

ChapKhoone/account/forms.py
from dataclasses import field
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm, ReadOnlyPasswordHashField
from .models import CustomUser, EvidenceStamp, Profile



class CustomUserCreationForm(UserCreationForm):

    class Meta:
            model = CustomUser
            fields = ('email', 'username', 'phone', 'password1', 'password2')
            
            widgets = {
                'phone': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'نام کاربر'}),
                'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder':'ایمیل'}),
                'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'نام کاربری'}),
                'password1': forms.Textarea(attrs={'class': 'form-control', 'placeholder':'رمز عبور'}), 
                'password2': forms.Textarea(attrs={'class': 'form-control', 'placeholder':'تکرار رمز عبور'}),
            }




class LoginForm(AuthenticationForm):
    
    username = forms.CharField(label="نام کاربری/شماره همراه/ایمیل",widget=forms.TextInput(attrs={'autofocus': True, 'class': 'form-control', 'placeholder':'نام کاربری/شماره همراه/ایمیل'}))
    
    
    
    
class VerifyForm(forms.Form):
    
    otp_code = forms.CharField(label='کد تایید', max_length=6, required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'کد تایید'}),
                        error_messages = {
                            'required' : 'این فیلد الزامی میباشد',
                            'max_length' : 'کاراکتر بیش از حد مجاز '
                        }
    
                    )
    
    
    
    
class ContactForm(forms.Form):
    name = forms.CharField(max_length=80, label='نام و نام خانوادگی')
    subject = forms.CharField(max_length=80, label='عنوان')
    message = forms.CharField(widget=forms.Textarea, label='پیام')
    email = forms.EmailField(label='ایمیل')
    
    
    
    
    
class UserChangeForm(UserChangeForm):
    password = ReadOnlyPasswordHashField(label='رمز ورود',
                                         widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder':'نام کاربر'}),
        help_text=(
            '.متاسفانه قادر به نمایش رمز عبور شما نیستیم'
            'ولی برای تغییر ان میتواید از.'
            '<a href="{}">این لینک</a>.'
            'استفاده کنید'
            
        ),
    )

    class Meta:
        model = Profile
        fields = ('description', 'first_name', 'last_name', 'address', 'age', 'sexuality', 'image', 'city', 'password')





class EvidencStampForm(forms.ModelForm):

    class Meta:
        model = EvidenceStamp
        fields = ['evidence', 'evidence2', 'sketch_stamp', 'note', 'is_framework']

ChapKhoone/account/templates/base/contant-us.html
{% include "base-dashboard.html" %}

{% load static %}
{% load widget_tweaks %}

{% block content %}


    <section class="no-padding">

        <div class="map" data-latitude="35.6878671" data-longitude="51.3536664" data-style="light" data-info="سلام از &lt;br&gt; چاپ آنلاین" data-height-lg="500" data-height-xs="200" data-height-sm="300"></div>
    
    </section>
    


<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h3 class="text-uppercase">در تماس باشید</h3>
                <p>شادترین زمان روز!. لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم، لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم، لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم.</p>
                <p>شادترین زمان روز!. لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم، لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم، لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم. یک داستان واقعی که هرگز گفته نشد!. لورم ایپسوم متن ساختگی با تولید سادگی.
                    لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم، لورم ایپسوم متن ساختگی با تولید سادگی.</p>
                <div class="row m-t-40">
                <div class="col-lg-6">
                    <address>
                        <strong>شرکت پولو</strong><br>
                                تهران، میدان آزادی<br>
                                خیابان آزادی، پلاک 7<br>
                                <abbr title="Phone">تلفن:</h4> 02155667788
                    </address>
                </div>
                <div class="col-lg-6">
                    <address>
                        <strong>دفتر پولو</strong><br>
                                تهران، میدان آزادی<br>
                                خیابان آزادی، پلاک  7<br>
                                 <abbr title="Phone">تلفن:</h4> 02155667788
                     </address>
                </div>
            </div>
        <div class="social-icons m-t-30 social-icons-colored">
            <ul>
                <li class="social-facebook"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                <li class="social-twitter"><a href="#"><i class="fab fa-twitter"></i></a></li>
                <li class="social-google"><a href="#"><i class="fab fa-google-plus-g"></i></a></li>
                <li class="social-pinterest"><a href="#"><i class="fab fa-pinterest"></i></a></li>
                <li class="social-vimeo"><a href="#"><i class="fab fa-vimeo"></i></a></li>
                <li class="social-linkedin"><a href="#"><i class="fab fa-linkedin"></i></a></li>
            </ul>
        </div>
    </div>
    <div class="col-lg-6">
        <form class="widget-contact-form" novalidate action="" role="form" method="post">{% csrf_token %}
            <div class="row">
                <div class="form-group col-md-6">
                    <label for="name">نام</label>
                    {{ form.name|attr:"placeholder:اسم خود را وارد کنید"|attr:"aria-required:true"|attr:"type:text"|attr:"class:form-control required name"|attr:"required" }}
                </div>
                <div class="form-group col-md-6">
                    <label for="email">ایمیل</label>
                    {{ form.email|attr:"placeholder:ایمیل خود را وارد کنید"|attr:"type:email"|attr:"class:form-control required email"|attr:"required" }}
                </div>
            </div>
            <div class="row">
                <div class="form-group col-md-12">
                    <label for="subject">موضوع شما</label>
                    {{ form.subject|attr:"placeholder:موضوع خود را بنویسید"|attr:"id:subject"|attr:"type:text"|attr:"class:form-control required"|attr:"required" }}
                </div>
            </div>
                <div class="form-group">
                    <label for="message">پیام</label>
                    {{ form.message|attr:"placeholder:پیام خود را بنویسید"|attr:"rows:5"|attr:"id:message"|attr:"type:text"|attr:"class:form-control required"|attr:"required" }}
                </div>
                    
                <button class="btn" type="submit" id="form-submit"><i class="fa fa-paper-plane"></i>&nbsp;ارسال پیام</button>
        </form>
    </div>
    </div>
    </div>
</section> 

<footer id="footer">
    <div class="footer-content">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="icon-box effect small clean">
                        <div class="icon">
                            <a href="#"><i class="icon-clock"></i></a>
                        </div>
                        <h3>روزهای کاری</h3>
                        <p><strong>شنبه - چهارشنبه</strong>
                            <br>10:00 صبح - 11:00 عصر</p>
                        <p><strong>پنج شنبه - جمعه</strong>
                            <br>10:00 صبح - 04:00 عصر</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="icon-box effect small clean">
                        <div class="icon">
                            <a href="#"><i class="fas fa-map-marker-alt"></i></a>
                        </div>
                        <h3>موقعیت مکانی شرکت</h3>
                        <p><strong>آدرس شرکت : </strong>
                            <br> تهران، میدان آزادی
                            <br> خیابان آزادی، پلاک 7
                            <br>
                            <br>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="icon-box effect small clean">
                        <div class="icon">
                            <a href="#"><i class="icon-phone"></i></a>
                        </div>
                        <h3>شماره تماس شرکت</h3>
                        <p><strong>تلفن : </strong>
                            <br> 02155667788
                            <br> 02166554433
                            <br>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright-content">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">

                    <div class="social-icons social-icons-colored float-left">
                        <ul>
                            <li class="social-rss"><a href="#"><i class="fa fa-rss"></i></a></li>
                            <li class="social-facebook"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                            <li class="social-twitter"><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li class="social-vimeo"><a href="#"><i class="fab fa-vimeo"></i></a></li>
                            <li class="social-youtube"><a href="#"><i class="fab fa-youtube"></i></a></li>
                            <li class="social-pinterest"><a href="#"><i class="fab fa-pinterest"></i></a></li>
                            <li class="social-gplus"><a href="#"><i class="fab fa-google-plus-g"></i></a></li>
                        </ul>
                    </div>

                </div>
                <div class="col-lg-6">
                    <div class="copyright-text text-center">&copy; کپی رایت 2023 <a href='bamaitc.com/'>bamaitc</a> - تمامی حقوق محفوظ است
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>



    

{% endblock content %}


<script type='text/javascript' src='https://maps.googleapis.com/maps/api/js?key=AIzaSyDKXKdHQdtqgPVl2HI2RnUa_1bjCxRCQo4&callback=initMap'></script>
<script type="text/javascript" src="{% static 'plugins/gmap3/gmap3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/gmap3/map-styles.js' %}"></script>

ChapKhoone/account/templates/base/error-404.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>صفحه یافت نشد</title>
	<!-- start css and style -->
	<link rel="stylesheet" href="{% static 'page-404/css/bootstrap-rtl.css' %}">
	<link type="text/css" href="{% static 'page-404/css/style.css' %}" rel="stylesheet" />
</head>
<body>
<div class="container">
	<div class="row">
		<div class="col-lg-8 col-lg-offset-2 col-xs-12">
			<div class="wrapper">
				<!-- start text box -->
				<div class="TextHolder">
					<div class="Texts">
						<div class="FourOhFour">404</div>
						<div class="Maybe">اوه ... شاید ...<span>مشکلی پیش اومده باشه</span></div>
						<div class="Bad">متاسفانه صفحه مورد نظر پیدا نشد !</div>
						<a href="{% url 'landing-home' %}"><div class="Return">بازگشت به صفحه نخست</div></a>
					</div>
				</div>
				<!-- end text box -->

				<!-- start monster details -->
				<div class="Body">
					<div class="LeftEye"></div>
					<div class="RightEye"></div>
					<div class="EyeShadows"></div>
					<div class="Mouth"></div>
					<div class="MouthShadows"></div>
					<div class="Theet"></div>
					<div class="BodyTexture"></div>
				</div>
				<div class="Horns">
					<div class="HornsExtras"></div>
				</div>
				<div class="LeftHand"></div>
				<div class="RightHand"></div>
				<!-- end monster details -->
			</div>
		</div>
	</div>
</div>

	<!-- start java script -->
	<script src="{% static 'page-404/js/jquery-3.1.1.min.js' %}"></script>
	<script src="{% static 'page-404/js/bootstrap.min.js' %}"></script>
	<script  src="{% static 'page-404/js/scripts.js' %}"></script>
</body><!-- This template has been downloaded from Webrubik.com -->
</html>

ChapKhoone/account/templates/base/stamp-category.html
{% include "base-dashboard.html" %}

{% load static %}

{% block content %}

{% if stamp %}


<section id="page-content">
    <div class="container">
        <div class="row">

            <div class="col-lg-6 p-t-10 m-b-20">
                <h3 class="m-b-20">{{ stamp.name }}</h3>
                <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم، لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم
                    لورم ایپسوم متن ساختگی با تولید سادگی.</p>
            </div>

            <div class="sidebar sticky-sidebar col-lg-3">


                <div class="widget  widget-tags">
                    <h4 class="widget-title">دسته بندی</h4>
                    <div class="tags">
                        {% for item in category_all %}
                        <a href="{{ item.get_absolute_url }}">{{ item }}</a>
                        {% endfor %}
                    </div>
                </div>

            </div>

            <div class="content col-lg-9">

                <div class="row">

                    {% for item in stamp.stamp_set.all %}
                    <div class="col-lg-4">
                        <div class="card">
                            <img class="card-img-top" src="/media/{{ item.image }}" alt="Card image cap">
                            <div class="card-body">
                                <h5 class="card-title">{{ item.name }}</h5>
                                <p class="card-text">{{ item.description }}
                                </p>
                                <a href="{% url 'stamp-detail' slug=item.slug %}" class="btn btn-primary">خرید</a>
                            </div>
                            <div class="card-footer">
                                <small class="text-muted">قیمت: {{ item.price }}</small>
                            </div>
                        </div>
                    </div>
                    {% endfor %}


                    {% else %}

                    <section class="m-t-80 p-b-150">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="page-error-404 text-center">500</div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="text-left">
                                        <h1 class="text-medium">خطای سرور!</h1>
                                        <p class="lead">متأسفیم، مشکلی در سرور ما وجود دارد.</p>
                                        <div class="seperator m-t-20 m-b-20"></div><button onclick="window.location.reload()"
                                            class="btn" type="button">بارگذاری مجدد صفحه</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                    {% endif %}

                </div>
            </div>

        </div>
    </div>
</section>


<footer id="footer">
    <div class="footer-content">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <div class="icon-box effect small clean">
                        <div class="icon">
                            <a href="#"><i class="icon-clock"></i></a>
                        </div>
                        <h3>روزهای کاری</h3>
                        <p><strong>شنبه - چهارشنبه</strong>
                            <br>10:00 صبح - 11:00 عصر</p>
                        <p><strong>پنج شنبه - جمعه</strong>
                            <br>10:00 صبح - 04:00 عصر</p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="icon-box effect small clean">
                        <div class="icon">
                            <a href="#"><i class="fas fa-map-marker-alt"></i></a>
                        </div>
                        <h3>موقعیت مکانی شرکت</h3>
                        <p><strong>آدرس شرکت : </strong>
                            <br> تهران، میدان آزادی
                            <br> خیابان آزادی، پلاک 7
                            <br>
                            <br>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="icon-box effect small clean">
                        <div class="icon">
                            <a href="#"><i class="icon-phone"></i></a>
                        </div>
                        <h3>شماره تماس شرکت</h3>
                        <p><strong>تلفن : </strong>
                            <br> 02155667788
                            <br> 02166554433
                            <br>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="copyright-content">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">

                    <div class="social-icons social-icons-colored float-left">
                        <ul>
                            <li class="social-rss"><a href="#"><i class="fa fa-rss"></i></a></li>
                            <li class="social-facebook"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                            <li class="social-twitter"><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li class="social-vimeo"><a href="#"><i class="fab fa-vimeo"></i></a></li>
                            <li class="social-youtube"><a href="#"><i class="fab fa-youtube"></i></a></li>
                            <li class="social-pinterest"><a href="#"><i class="fab fa-pinterest"></i></a></li>
                            <li class="social-gplus"><a href="#"><i class="fab fa-google-plus-g"></i></a></li>
                        </ul>
                    </div>

                </div>
                <div class="col-lg-6">
                    <div class="copyright-text text-center">&copy; کپی رایت 2023 <a href='bamaitc.com/'>bamaitc</a> - تمامی حقوق محفوظ است
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>


{% endblock content %}